### ISSUE TITLE
Schlage top black line too low

### ISSUE THREAD

**Issue by algotastic** [deviantollam/decoding#4]
As mentioned [here](https://youtu.be/KU6FJnbkeLA?t=1189), the top black line on the Schlage decoding template is not the correct distance apart from its neighbors.

**Comment by deviantollam** [comment]
double-checked and according to all bitting code data, these lines (including the black line) appear to be the right position.  the black line should not be equidistant in the same spacing as the grey and blue lines are from one another.

i'm not 100% sure why it was giving us some trouble in that KringleCon talk, however.
